site_name: VMware DORA Evidence
site_description: A comprehensive tool for collecting and analyzing DORA metrics from VMware environments
site_author: VMware DORA Evidence Team
site_url: https://uldyssian-sh.github.io/vmware-dora-evidence

repo_name: uldyssian-sh/vmware-dora-evidence
repo_url: https://github.com/uldyssian-sh/vmware-dora-evidence
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Quick Start: tutorials/quick-start.md
  - User Guide:
    - DORA Metrics: guides/dora-metrics.md
    - Data Collection: guides/data-collection.md
    - Reporting: guides/reporting.md
    - Monitoring: guides/monitoring.md
  - Tutorials:
    - Basic Usage: tutorials/basic-usage.md
    - Advanced Configuration: tutorials/advanced-configuration.md
    - Custom Integrations: tutorials/custom-integrations.md
    - Troubleshooting: tutorials/troubleshooting.md
  - API Reference:
    - Overview: api/overview.md
    - Collectors: api/collectors.md
    - Analyzers: api/analyzers.md
    - Reporters: api/reporters.md
    - Integrations: api/integrations.md
  - Development:
    - Contributing: ../CONTRIBUTING.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Release Process: development/release-process.md
  - About:
    - License: ../LICENSE
    - Changelog: ../CHANGELOG.md
    - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uldyssian-sh/vmware-dora-evidence
    - icon: fontawesome/solid/book
      link: https://uldyssian-sh.github.io/vmware-dora-evidence
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js